version: '3.8'

services:
  app:
    image: iamsurendrap/marketplace-web-client:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: angular-app-dev
    ports:
      - "80:4200"
    volumes:
      - .:/app 
      - /app/node_modules
    environment:
      - NODE_ENV=development
